### ISSUE TITLE
It shows update available always

### ISSUE THREAD

**Issue by Anand3777** [feilfeilundfeil/flutter_in_app_update#14]
Hi i implemented in_app_update: ^1.1.6,

I changed my package name and my code below

**// Platform messages are asynchronous, so we initialize in an async method.
  Future<void> checkForUpdate() async {
    InAppUpdate.checkForUpdate().then((info) {
      setState(() {
        _updateInfo = info;
        if (_updateInfo.updateAvailable == true) {
          InAppUpdate.performImmediateUpdate().catchError((e) => _showError(e));
        }
      });
    }).catchError((e) => _showError(e));
  }**

My Issues is after performImmediateUpdate app is opening again it checks and its looping the process i dont know how to stop once perform update

always response getting 

**info:------>InAppUpdateState{updateAvailable: true, immediateUpdateAllowed: true, flexibleUpdateAllowed: true, availableVersionCode: 3}**

**Comment by jonasbark** [comment]
So your versionCode after updating is 3? And it tries to update to a versionCode 3 again?
How are you testing this with debug on? That might be a problem.

**Comment by penkz** [comment]
@Anand3777 This happened to me while running the app in profile mode, it seems that you can't update the app while profiling it. I build an APK and the app was updated then.

@jonasbark  Also I have a similar question, does immediateUpdateAllowed and flexibleUpdateAllowed always returns true by default? If so, how do I pick what kind of update to perform?

Thanks!

**Comment by jonasbark** [comment]
@penkz I'm sure the official documentation can answer that! But if both are true then you're free to pick however you like your users to have the in app update dialog displayed!

**Comment by Anand3777** [comment]
> @Anand3777 This happened to me while running the app in profile mode, it seems that you can't update the app while profiling it. I build an APK and the app was updated then.
> 
> @jonasbark Also I have a similar question, does immediateUpdateAllowed and flexibleUpdateAllowed always returns true by default? If so, how do I pick what kind of update to perform?
> 
> Thanks!

I ll check and update you shortly

**Comment by Anand3777** [comment]
> So your versionCode after updating is 3? And it tries to update to a versionCode 3 again?
> How are you testing this with debug on? That might be a problem.

I'm checking debug mode

**Comment by jonasbark** [comment]
Please check the https://developer.android.com/guide/app-bundle/in-app-updates#troubleshoot section. Afaik it's perfectly valid to show true in debug mode.

**Comment by JankoLancer** [comment]
I have this same problem. Strange but I reproducing this only on Samsung devices.
