### ISSUE TITLE
Inmediate update don't update the app

### ISSUE THREAD

**Issue by davidgcs11** [feilfeilundfeil/flutter_in_app_update#20]
Hi.
I used Immediate Update, the Google Play screen appears and downloads the update, after it's completed the app is restarted but there's no update in the code version.
After the 'update' local app version remains the same.

There's no error going on, so i dont know exactly what to do.

Here the loop video:
https://streamable.com/9v3pt

**Comment by don-prog** [comment]
@davidgcs11 hello, I had the same issue, please check this for solution: https://github.com/SanojPunchihewa/InAppUpdater/issues/14

**Comment by davidgcs11** [comment]
@don-prog thanks!
