### ISSUE TITLE
Delays compared to Play Store application

### ISSUE THREAD

**Issue by mbenci** [feilfeilundfeil/flutter_in_app_update#23]
I'm using the 1.1.7 version of in_app_update.

I've noticed that systematically the Play Store application suggests an update before the plugin.
It is necessary more time (from minutes to hours sometimes) so that the update is available also for the plugin 
I'd like to know if others have noticed the same behavior.

Thanks

**Comment by jonasbark** [comment]
This issue has nothing to do with the Flutter plugin but with Googles In App Update functionality. Stackoverflow would be a better place to address this.
