### ISSUE TITLE
PlatformException - Install Error(-3): The API is not available on this device. 

### ISSUE THREAD

**Issue by alyyasser** [feilfeilundfeil/flutter_in_app_update#25]
i've got this error today:

> PlatformException(Install Error(-3): The API is not available on this device. (https://developer.android.com/reference/com/google/android/play/core/install/model/InstallErrorCode#ERROR_API_NOT_AVAILABLE), null, null)

**Comment by MaskyS** [comment]
You probably want to post the logs of `flutter doctor -v`

**Comment by jonasbark** [comment]
That would be helpful indeed. I'm closing this anyway because this has nothing to do with the Flutter plugin but moreover the fact that you're trying to use this on an unsupported device (e.g. no play services installed).
Use stackoverflow to ask questions about the underlying library from google.

**Comment by alyyasser** [comment]
hold on a sec.
my bad, i was in rush and didn't supply some basic information with it, im sorry.

first, here is `flutter doctor -v` output:

> [√] Flutter (Channel master, v1.13.6-pre.44, on Microsoft Windows [Version 10.0.18363.719], locale en-ID)
>     • Flutter version 1.13.6-pre.44 at D:\Development\flutter
>     • Framework revision e768c92fbc (3 months ago), 2019-12-30 17:12:19 -0800
>     • Engine revision bdc9708d23
>     • Dart version 2.8.0 (build 2.8.0-dev.0.0 c547f5d933)
> 
> [!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
>     • Android SDK at D:\Development\Android\Sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-29, build-tools 29.0.2
>     • ANDROID_HOME = C:\Users\ngekn\.android
>     • Java binary at: D:\Development\JetBrains\Toolbox\apps\AndroidStudio\ch-1\193.6254973\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
>     X Android license status unknown.
>       Try re-installing or updating your Android SDK Manager.
>       See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.
> 
> [√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.4.2)
>     • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
>     • Visual Studio Community 2019 version 16.4.29613.14
> 
> [√] Android Studio (version 4.0)
>     • Android Studio at D:\Development\JetBrains\Toolbox\apps\AndroidStudio\ch-1\193.6254973
>     • Flutter plugin version 42.2.2
>     • Dart plugin version 192.7761
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
> 
> [√] VS Code, 64-bit edition (version 1.42.1)
>     • VS Code at C:\Program Files\Microsoft VS Code
>     • Flutter extension version 3.8.1
> 
> [√] Connected device (2 available)
>     • ONEPLUS A5010 • 3d358a65 • android-arm64 • Android 9 (API 28)

second, the **FACT** is, i was running the app in my own device, OnePlus 5T, running Android 9, which obviously, had play service installed.

third, another **FACT** is, the same exception raised when i run the app using another device, OnePlus 7, running Android 10, which, again, obviously, had play service installed.

**Comment by alyyasser** [comment]
alright, after a bit more research, i found this:
https://stackoverflow.com/questions/60718191/in-app-update-gives-installexception-error-api-not-available
and this:
https://issuetracker.google.com/issues/151648849

thank you.

**Comment by rickynugroho** [comment]
I also having this issue, the function checkForUpdate() was working normally until 2 days ago (17 Mar 2020). Also found the same link as @alyyasser. 

Our team did not use emulator for testing, we always use external android phone with logged in google account and working google play app. We use the same devices, and no problem was found before.

The good news is, our current production app on google play did not have this issue, only apk that debugged or apk package that created after 17 Mar 2020 have this problem.

Hope we  we see good news from google issue tracker.
Thank you.

**Comment by dfdgsdfg** [comment]
Same here. It just works well, but suddenly error appears.

```
I/PlayCore(16120): UID: [10186]  PID: [16120] AppUpdateService : requestUpdateInfo(----.-----.---)
I/PlayCore(16120): UID: [10186]  PID: [16120] AppUpdateService : Initiate binding to the service.
I/PlayCore(16120): UID: [10186]  PID: [16120] AppUpdateService : ServiceConnectionImpl.onServiceConnected(ComponentInfo{com.android.vending/com.google.android.finsky.installservice.DevTriggeredUpdateService})
I/PlayCore(16120): UID: [10186]  PID: [16120] AppUpdateService : linkToDeath
I/PlayCore(16120): UID: [10186]  PID: [16120] OnRequestInstallCallback : onRequestInfo
I/PlayCore(16120): UID: [10186]  PID: [16120] AppUpdateService : Unbind from service.
I/flutter (16120): UpdateBloc: _androidCheckUpdate: PlatformException(Install Error(-3): The API is not available on this device. (https://developer.android.com/reference/com/google/android/play/core/install/model/InstallErrorCode#ERROR_API_NOT_AVAILABLE), null, null)
```

@alyyasser I don't have any issue with package name like you suggested link.

**Comment by zgramming** [comment]
Same Error Here. 

### Log Error 
```
Exception has occurred.
PlatformException (PlatformException(Install Error(-3): The API is not available on this device. (https://developer.android.com/reference/com/google/android/play/core/install/model/InstallErrorCode#ERROR_API_NOT_AVAILABLE), null, null))

Launching lib\main.dart on Redmi Note 4 in debug mode...
Parameter format not correct -
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
√ Built build\app\outputs\flutter-apk\app-debug.apk.
V/BoostFramework( 8838): BoostFramework() : mPerf = com.qualcomm.qti.Performance@c6e9049
I/PlayCore( 8838): UID: [10420]  PID: [8838] AppUpdateService : requestUpdateInfo(id.zeffry.atur_semua_aktifitas)
I/PlayCore( 8838): UID: [10420]  PID: [8838] AppUpdateService : Initiate binding to the service.
I/PlayCore( 8838): UID: [10420]  PID: [8838] AppUpdateService : requestUpdateInfo(id.zeffry.atur_semua_aktifitas)
I/PlayCore( 8838): UID: [10420]  PID: [8838] AppUpdateService : Initiate binding to the service.
I/PlayCore( 8838): UID: [10420]  PID: [8838] AppUpdateService : ServiceConnectionImpl.onServiceConnected(ComponentInfo{com.android.vending/com.google.android.finsky.installservice.DevTriggeredUpdateService})
I/PlayCore( 8838): UID: [10420]  PID: [8838] AppUpdateService : ServiceConnectionImpl.onServiceConnected(ComponentInfo{com.android.vending/com.google.android.finsky.installservice.DevTriggeredUpdateService})
I/PlayCore( 8838): UID: [10420]  PID: [8838] AppUpdateService : linkToDeath
I/PlayCore( 8838): UID: [10420]  PID: [8838] AppUpdateService : linkToDeath
I/PlayCore( 8838): UID: [10420]  PID: [8838] OnRequestInstallCallback : onRequestInfo
I/PlayCore( 8838): UID: [10420]  PID: [8838] AppUpdateService : Unbind from service.
I/PlayCore( 8838): UID: [10420]  PID: [8838] OnRequestInstallCallback : onRequestInfo
I/PlayCore( 8838): UID: [10420]  PID: [8838] AppUpdateService : Unbind from service.
```
