### ISSUE TITLE
PlatformException(Failed to bind to the service., null, null) while calling checkForUpdate

### ISSUE THREAD

**Issue by DhavalRKansara** [feilfeilundfeil/flutter_in_app_update#27]
PlatformException(Failed to bind to the service., null, null) while calling `checkForUpdate`

**Code:**

```
 @override
  void initState() {
    if(Platform.isAndroid){
      checkForUpdate();
    }
    super.initState();
  }

  Future<void> checkForUpdate() async {
    await InAppUpdate.checkForUpdate().then((info) {
        print("update available");
    }).catchError((e) => print(" error is ${e.toString()}"));
  }

```

**Exception:** 

error is PlatformException(Failed to bind to the service., null, null)

**Comment by yeahse** [comment]
same here

**Comment by paurakhsharma** [comment]
I am getting the same error  😐

**Comment by paurakhsharma** [comment]
Turns out it only happens in development mode, if you publish the app in the play store, it works fine.

To test this use [Internal App Sharing](https://play.google.com/apps/publish/internalappsharing/)

**Comment by jonasbark** [comment]
Good to know - thank you.
For those that are affected by this issue - can you delay calling InAppUpdate.checkForUpdate for a bit and see if it works more reliably?

**Comment by jonasbark** [comment]
Please check version 1.1.8.
