### ISSUE TITLE
Flexible update issue

### ISSUE THREAD

**Issue by rahuldange09** [feilfeilundfeil/flutter_in_app_update#28]
Hello,
After checking for update, Flexible update dialog comes. But after clicking on update it starts as full screen instead of doing update in background as word flexible says. 
It starts full screen and even pressing back button it again launched automatically to full screen. 
As I saw in other app flexible one works in background.

As I another issue InAppUpdate caused trouble. It's not showing any update even new update is on play store. After some days it shows for older once. This caused big blunder as I was dependent on it.

Can you help with this.
Thank you

**Comment by rahuldange09** [comment]
Any update on this?

**Comment by rahuldange09** [comment]
@feilfeilundfeil any confirmation from your side?

**Comment by themobilecoder** [comment]
Bump on this issue.

The dialog for flexible update is shown correctly, but clicking on the update shows the fullscreen (immediate update) instead.

![screen1](https://user-images.githubusercontent.com/7467309/83350939-12d1bd00-a383-11ea-82d0-df0da05db66a.png)
![screen2](https://user-images.githubusercontent.com/7467309/83350937-106f6300-a383-11ea-8a3b-5dab93f6a068.png)


Please see the attached screenshot.

The code I am using is this:

```
      InAppUpdate.checkForUpdate().then((update) {
        if (update.updateAvailable) {
          InAppUpdate.startFlexibleUpdate();
        } 
      }).catchError((e) {
        print(e);
      });
```

**Comment by rubenvereecken** [comment]
I get exactly the same. I had a look at the relevant bit of code and can't figure out what could cause it.

**Comment by rubenvereecken** [comment]
I have a feeling this line might be to blame
https://github.com/feilfeilundfeil/flutter_in_app_update/blob/master/android/src/main/kotlin/de/ffuf/in_app_update/InAppUpdatePlugin.kt#L141
