### ISSUE TITLE
Fix updateType

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [feilfeilundfeil/flutter_in_app_update#3]
I think that you are not corretly setting the `updateType`, which causes it to always be `null`.

https://github.com/feilfeilundfeil/flutter_in_app_update/blob/e6d0ad88b4a22be93cc71ecd1f9ba56b4a26bc1a/android/src/main/kotlin/de/ffuf/in_app_update/InAppUpdatePlugin.kt#L125

I would create a pull request that fixes this on the Dart side, i.e. change the properties to be `immediateAllowed` and `flexibleAllowed` as I think that it is better to work with than checking `updateType` for `null`.  
If I am missing something, please tell me.

**Comment by jonasbark** [comment]
True, thanks for spotting it!

**Comment by creativecreatorormaybenot** [comment]
@jonasbark I will create the PR in a second. I also did some refactoring, however, I can obviously adjust it.
