### ISSUE TITLE
Issues getting update details 

### ISSUE THREAD

**Issue by OLayemii** [feilfeilundfeil/flutter_in_app_update#36]
I'm trying to check for updates, using the example code from the repo, I've installed an older version on my device and uploaded a newer one on internal test track 
![Screenshot_20200519_030647](https://user-images.githubusercontent.com/11563148/82277053-d8c5eb80-997e-11ea-910f-87595d151e81.jpg)

This shows there's an update available, 

But when I run the app 

![Screenshot_20200519_030740](https://user-images.githubusercontent.com/11563148/82277086-eda27f00-997e-11ea-8907-52fbec3930d9.jpg)

This is what I get, any help?

**Comment by mdazharuddin1011999** [comment]
How did you solve this. I am facing the same issue. My app which is an **older version installed via play store** shows ```updateAvailable: false``` even when play store says update is available.  
  
Play Store:
![IMG_20200601_185058](https://user-images.githubusercontent.com/42082172/83413146-f8f2b180-a438-11ea-914c-04b71fde83f6.jpg)
***
App:
![IMG_20200601_182815](https://user-images.githubusercontent.com/42082172/83413175-0740cd80-a439-11ea-9cbb-5d167659ce4b.jpg)
***
My code:
```dart
class _TnPState extends State<TnP> {
  ThemeBloc _themeBloc;
  FirebaseMessaging _firebaseMessaging;
  NotificationBloc _notificationBloc;
  String _test;

  @override
  void initState() {
    _themeBloc = ThemeBloc();
    _firebaseMessaging = FirebaseMessaging();
    _notificationBloc = NotificationBloc();
    _firebaseMessaging.configure(
      onMessage: (notification) async => _notificationBloc.yes(),
      onResume: (notification) async => _notificationBloc.yes(),
      onLaunch: (notification) async => _notificationBloc.yes(),
    );
    checkForUpdate();
    super.initState();
  }

  Future<void> checkForUpdate() async {
    InAppUpdate.checkForUpdate().then((info) {
      String display = info.toString();
      setState((){
        _test = display;
      });
    });
  }

  @override
  Widget build(BuildContext context) {
    return StreamBuilder<AppTheme>(
      stream: _themeBloc.themeStream,
      initialData: AppTheme.Light,
      builder: (context, AsyncSnapshot<AppTheme> snapshot) {
        return MaterialApp(
          title: 'TnP',
          debugShowCheckedModeBanner: false,
          theme: appThemeData[snapshot.data],
          home: _test==null ?
                Container() : 
                InAppUpdateScreen(display: _test),//SplashScreen(),
        );
      },
    );
  }
}
```

**Comment by mdazharuddin1011999** [comment]
Never mind. It started working the next day. I think it was the problem from playstore not the plugin.

**Comment by OLayemii** [comment]
Yes same as me, I just had to wait for almost a day.

**Comment by mdazharuddin1011999** [comment]
I figured it out! The plugin won't show update available until playstore shows update available in *My apps & games* section. So just open My apps & games, wait for your app to show up and try it will work!

**Comment by OLayemii** [comment]
Yes, I noticed that too, and that delays upto a day atimes.
