### ISSUE TITLE
Will completeFlexibleUpdate update app UI

### ISSUE THREAD

**Issue by KevinYan12138** [feilfeilundfeil/flutter_in_app_update#38]
I want to ask if I call completeFlexibleUpdate, will the app UI change to the newest version? Or do I have to ask the user to restart the app?

**Comment by KohlMeister** [comment]
Hey Kevin,
I believe you'll need to ask the user to restart the app.
![image](https://user-images.githubusercontent.com/22916714/85879126-09c3e800-b797-11ea-8496-7839d5e1d909.png)
