### ISSUE TITLE
Is it possible to get in-app update priority?

### ISSUE THREAD

**Issue by rubenvereecken** [feilfeilundfeil/flutter_in_app_update#40]
Hi, I absolutely love the simplicity of this plugin. I just copied over the bit of the example to get `AppUpdateInfo` and got started. I had already figured out a versioning scheme that I was planning on using (based on semver), but then I noticed that in-app updates can have a priority associated with them. I don't really need this priority but it _might_ be a convenience to decide between flexible and required updates.

Is there any way to gain access to this priority? I assume it's stored close to where the other data lives that `checkForUpdate` grabs.

Anyway, I'll continue with my semver solution. Seriously, great work.

**Comment by ycv005** [comment]
@rubenvereecken Could you share the example of your code, I am confused. We have to use code from the example and we don't need to check for any version either within app or request from a server. thanks

**Comment by rubenvereecken** [comment]
Well, I chose to do version checking. We use semantic versioning on the version string. If the latest available version represents a breaking change then it's high priority and it should be a forced update. If it's just a minor non-breaking update then it becomes optional. 

I side-tracked. Version strings are not available through in-app updates. What _is_ available though is update priority which is an integer between 1 and 5 which you can set when uploading your update to Play. It would be nice to have access to this priority as an alternative means to determine whether the update should be forced or optional.

**Comment by ycv005** [comment]
Hey @rubenvereecken , for now I want to simply implement this feature. Do i have to just implement example code and it will work Or i need to implement more things, if yes, then what extra thing I need to implement. I am asking becuase it is not working while debugging.

**Comment by rubenvereecken** [comment]
Not entirely sure what you're asking. If you're curious to implement it, dig into the Kotlin code. You'll see it accesses an AppUpdateInfo object. If you head over to Android's developer docs you'll see that that object has quite a few more fields then this Flutter library is grabbing. You could just grab a few more fields in the same way it's already done.

**Comment by fuadarradhi** [comment]
@jonasbark we need this feature please..
seem `info.updatePriority()` can be expose
