### ISSUE TITLE
Unable to build with this lib.

### ISSUE THREAD

**Issue by rahuljidgedev** [feilfeilundfeil/flutter_in_app_update#47]
Running Gradle task 'assembleDebug'...
Note: /home/ekalpa/Android/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_database-4.1.1/android/src/main/java/io/flutter/plugins/firebase/database/MethodCallHandlerImpl.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
e: /home/ekalpa/Android/flutter/.pub-cache/hosted/pub.dartlang.org/in_app_update-1.1.11/android/src/main/kotlin/de/ffuf/in_app_update/InAppUpdatePlugin.kt: (29, 1): Class 'InAppUpdatePlugin' is not abstract and does not implement abstract member public abstract fun onActivityCreated(p0: Activity, p1: Bundle?): Unit defined in android.app.Application.ActivityLifecycleCallbacks
e: /home/ekalpa/Android/flutter/.pub-cache/hosted/pub.dartlang.org/in_app_update-1.1.11/android/src/main/kotlin/de/ffuf/in_app_update/InAppUpdatePlugin.kt: (129, 5): 'onActivityCreated' overrides nothing
e: /home/ekalpa/Android/flutter/.pub-cache/hosted/pub.dartlang.org/in_app_update-1.1.11/android/src/main/kotlin/de/ffuf/in_app_update/InAppUpdatePlugin.kt: (131, 5): 'onActivityPaused' overrides nothing
e: /home/ekalpa/Android/flutter/.pub-cache/hosted/pub.dartlang.org/in_app_update-1.1.11/android/src/main/kotlin/de/ffuf/in_app_update/InAppUpdatePlugin.kt: (133, 5): 'onActivityStarted' overrides nothing
e: /home/ekalpa/Android/flutter/.pub-cache/hosted/pub.dartlang.org/in_app_update-1.1.11/android/src/main/kotlin/de/ffuf/in_app_update/InAppUpdatePlugin.kt: (135, 5): 'onActivityDestroyed' overrides nothing
e: /home/ekalpa/Android/flutter/.pub-cache/hosted/pub.dartlang.org/in_app_update-1.1.11/android/src/main/kotlin/de/ffuf/in_app_update/InAppUpdatePlugin.kt: (137, 5): 'onActivitySaveInstanceState' overrides nothing
e: /home/ekalpa/Android/flutter/.pub-cache/hosted/pub.dartlang.org/in_app_update-1.1.11/android/src/main/kotlin/de/ffuf/in_app_update/InAppUpdatePlugin.kt: (139, 5): 'onActivityStopped' overrides nothing
e: /home/ekalpa/Android/flutter/.pub-cache/hosted/pub.dartlang.org/in_app_update-1.1.11/android/src/main/kotlin/de/ffuf/in_app_update/InAppUpdatePlugin.kt: (141, 5): 'onActivityResumed' overrides nothing

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':in_app_update:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by jonasbark** [comment]
Which flutter version?
You'll have to use a recent one

**Comment by rahuljidgedev** [comment]
flutter --version

Flutter 1.23.0-4.0.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision 83dd176777 (3 weeks ago) • 2020-09-22 12:04:44 -0700
Engine • revision 2abe69c608
Tools • Dart 2.10.0 (build 2.10.0-136.0.dev)

Is this version is correct?

**Comment by rovkinmax** [comment]
I have the same problem on the latest lib version

Flutter 1.22.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 84f3d28555 (7 дней назад) • 2020-10-15 16:26:19 -0700
Engine • revision b8752bbfff
Tools • Dart 2.10.2

**Comment by rovkinmax** [comment]
fast fix is set `compileSdkVersion 29`, In my project was `30`

**Comment by ivatar39** [comment]
Same problem

**Comment by Susheelkaram** [comment]
Any update on this?

I have been facing this issue as well.

**It works fine on Windows. But when I switch to Ubuntu and run pub get, I get this error**

`The plugin `in_app_update` requires your app to be migrated to the Android embedding v2. Follow the steps on https://flutter.dev/go/android-project-migration and re-run this command.`

I tried upgrading to latest version and  downgrade to lowest version I still get this issue.

Flutter doctor on Ubuntu:

`[✓] Flutter (Channel stable, 1.22.2, on Linux, locale en_IN)
    • Flutter version 1.22.2 at /home/susheel/flutter
    • Framework revision 84f3d28555 (4 months ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/susheel/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /home/susheel/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[!] Android Studio
    • Android Studio at /home/susheel/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
`

Using same flutter version on both windows and ubuntu.

**Comment by jonasbark** [comment]
Closing this - let me know if it's still happening
