### ISSUE TITLE
MissingPluginException

### ISSUE THREAD

**Issue by sasp1** [feilfeilundfeil/flutter_in_app_update#49]
I get an error "MissingPluginException(No implementation found for method checkForUpdate on channel in_app_update)" when running your example code and pressing the button "Check for update". I have tried to run flutter clean, uninstall app etc. but without luck. I have also been searching through open and closed issue but cannot find anything similar. Furthermore I have tried installing previous versions but this made no difference. Is there any specific android implementation details that I am missing? 

Edit: Also, even when publishing the app on Google Play I get this error. 

Thank you.

**Comment by canewsin** [comment]
same issue.

**Comment by jonasbark** [comment]
Please include your flutter doctor output.
Note that only flutter: ">=1.12.0 <2.0.0" is supported.

**Comment by canewsin** [comment]
flutter doctor -v
```
[√] Flutter (Channel stable, 1.22.0, on Microsoft Windows [Version 10.0.19041.508], locale en-IN)
    • Flutter version 1.22.0 at C:\flutter\1.0.0
    • Framework revision d408d302e2 (4 weeks ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0

 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0) 
    • Android SDK at D:\Android\SDK
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = D:\Android\SDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.50.1)
    • VS Code at C:\Users\PramUkesh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.1

[√] Connected device (1 available)
    • Redmi K20 Pro (mobile) • 270a97e6 • android-arm64 • Android 10 (API 29)

• No issues found!
```

**Comment by sasp1** [comment]
% flutter doctor -v 
[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Mac OS X 10.15.7 19H2 x86_64, locale en-DK)
    • Flutter version 1.23.0-18.1.pre at /Users/sebastian/development/flutter
    • Framework revision 198df796aa (9 days ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/sebastian/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin installed
    • Dart plugin version 202.7319.5

[✓] VS Code (version 1.49.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (1 available)
    • WAS LX1 (mobile) • PMF4C17824002990 • android-arm64 • Android 8.0.0 (API 26)

• No issues found!

**Comment by jonasbark** [comment]
Please provide a minimal reproducible example flutter project

**Comment by sasp1** [comment]
I have just copied the example code from flutter library page: 

`import 'dart:async';

import 'package:flutter/material.dart';
import 'package:in_app_update/in_app_update.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  AppUpdateInfo _updateInfo;

  GlobalKey<ScaffoldState> _scaffoldKey = new GlobalKey();

  bool _flexibleUpdateAvailable = false;

  @override
  void initState() {
    super.initState();
  }

  // Platform messages are asynchronous, so we initialize in an async method.
  Future<void> checkForUpdate() async {
    InAppUpdate.checkForUpdate().then((info) {
      setState(() {
        _updateInfo = info;
      });
    }).catchError((e) => _showError(e));
  }

  void _showError(dynamic exception) {
    _scaffoldKey.currentState.showSnackBar(SnackBar(content: Text(exception.toString())));
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        key: _scaffoldKey,
        appBar: AppBar(
          title: const Text('In App Update Example App'),
        ),
        body: Padding(
          padding: const EdgeInsets.all(8.0),
          child: Column(
            children: <Widget>[
              Center(
                child: Text('Update info: $_updateInfo'),
              ),
              RaisedButton(
                child: Text('Check for Update'),
                onPressed: () => checkForUpdate(),
              ),
              RaisedButton(
                child: Text('Perform immediate update'),
                onPressed: _updateInfo?.updateAvailable == true
                    ? () {
                  InAppUpdate.performImmediateUpdate().catchError((e) => _showError(e));
                }
                    : null,
              ),
              RaisedButton(
                child: Text('Start flexible update'),
                onPressed: _updateInfo?.updateAvailable == true
                    ? () {
                  InAppUpdate.startFlexibleUpdate().then((_) {
                    setState(() {
                      _flexibleUpdateAvailable = true;
                    });
                  }).catchError((e) => _showError(e));
                }
                    : null,
              ),
              RaisedButton(
                child: Text('Complete flexible update'),
                onPressed: !_flexibleUpdateAvailable
                    ? null
                    : () {
                  InAppUpdate.completeFlexibleUpdate().then((_) {
                    _scaffoldKey.currentState.showSnackBar(SnackBar(content: Text('Success!')));
                  }).catchError((e) => _showError(e));
                },
              )
            ],
          ),
        ),
      ),
    );
  }
}`

**Comment by jonasbark** [comment]
Thanks for letting me know! Please update to 1.1.13.

**Comment by cimplesid** [comment]
facing same on 2.0.0 version @jonasbark

**Comment by Pavel401** [comment]
facing same on 2.0.0 version @jonasbark

**Comment by hareendranmg** [comment]
Same for v3.0.0

**Comment by jonasbark** [comment]
You should always provide the output of `flutter doctor -v`, otherwise I can't help.

**Comment by hareendranmg** [comment]
[✓] Flutter (Channel stable, 2.10.2, on Ubuntu 20.04.4 LTS 5.13.0-30-generic, locale en_US.UTF-8)
    • Flutter version 2.10.2 at /home/hareendranmg/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (3 days ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/hareendranmg/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /home/hareendranmg/Android/Sdk
    • Java binary at: /snap/android-studio/119/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Android Studio (version 2021.1)
    • Android Studio at /snap/android-studio/119/android-studio
    • Flutter plugin version 64.1.2
    • Dart plugin version 211.7798
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.34.0

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by frankymbieleu** [comment]
same issue.

**Comment by razer-santhosh** [comment]
still facing the same issue in package **^4.1.4** - MissingPluginException(No implementation found for method checkForUpdate on channel in_app_update)...

**Comment by jonasbark** [comment]
Please provide an example project where this is reproducible

**Comment by razer-santhosh** [comment]
> Please provide an example project where this is reproducible
It's solved, when I reinstall the app, but show new error of Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: PlatformException(TASK_FAILURE, AppUpdateService : Binder has died., null, null)

**Comment by dinesh-ramailo** [comment]
I am also facing the similar issue recently. 
It's reported on the sentry.

MissingPluginException(No implementation found for method startFlexibleUpdate on channel de.ffuf.in_app_update/methods)

**Comment by ovresko** [comment]
exact same issue here
