### ISSUE TITLE
No podspec found for `in_app_update` in `.symlinks/plugins/in_app_update/ios`

### ISSUE THREAD

**Issue by ccamba** [feilfeilundfeil/flutter_in_app_update#50]
Hi, the latest version 1.1.13 not include in_app_update.podspec. I can't compile in ios

**Comment by jonasbark** [comment]
https://github.com/feilfeilundfeil/flutter_in_app_update/blob/master/pubspec.yaml#L23
iOS is not a supported platform. You might be using an old version of Flutter.

**Comment by ccamba** [comment]
I know that it is not supported for IOS, my project works with Android and IOS. Tell me how I configure 1.1.11 for IOS and 1.1.13 for Android

**Comment by ccamba** [comment]
My version of flutter is 1.22.2, your plugin up to version 1.1.11 could be compiled in IOS without problems.
If you can not do a podspec dummy for compatibility I will have to uninstall this package

**Comment by ccamba** [comment]
In your documentation you say that if you invoke this functionality in IOS you will get an exception, not that it will not compile directly
https://pub.dev/packages/in_app_update#ios

**Comment by jonasbark** [comment]
Please provide a minimal reproducible project so I can have a look - otherwise it's up to you to make sure your Flutter project is updated according to changes in plugin format

**Comment by ccamba** [comment]
Just go to https://pub.dev/packages/in_app_update/versions
Download version 1.1.11 and you will find that the .tar.gz contains the corresponding podspec in the ios directory. Since 1.1.13 does not have it, I copied the content of 1.1.11 in .symlinks / plugins / in_app_update / ios and it worked perfectly.

As you can see, I am only asking you to maintain compatibility in order to compile it.
You should remove from the documentation that can be compiled in ios if it will no longer be compatible

Cheers

**Comment by jonasbark** [comment]
Sure enough - thanks for the information. Can you try the fixes/50 branch?

**Comment by ccamba** [comment]
it's ok, thanks
