### ISSUE TITLE
No implementation found for method checkForUpdate on channel in_app_update

### ISSUE THREAD

**Issue by Nemasio** [feilfeilundfeil/flutter_in_app_update#51]
Hey, this exception is ocurring to me, anyone has any idea how to solve the issue?
It happens when checkForUpdate future function returns.
"No implementation found for method checkForUpdate on channel in_app_update"

Also when i now do FLUTTER RUN, says this:
The plugin `in_app_update` requires your app to be migrated to the Android embedding v2. Follow the steps on
https://flutter.dev/go/android-project-migration and re-run this command.

Im running Flutter version 1.20.4

`
void _actualizarAppAndroid(){

    print('Verificando si hay nueva version');
    InAppUpdate.checkForUpdate()
    .then((info) {
      setState(() {
        _updateInfo = info;

        if (_updateInfo?.updateAvailable == true) {
            print('Hay Update');

            InAppUpdate.startFlexibleUpdate()
              .then((_) {
                setState(() {
                  print('Comenzar flex Update');
                  _flexibleUpdateAvailable = true;
                  /*InAppUpdate.completeFlexibleUpdate().then((_) {
                          _scaffoldKey.currentState.showSnackBar(SnackBar(content: Text('Success!')));
                        }).catchError((e) => _showError(e));*/
                });
            }).catchError((e) => _showError(e));
        }
      });
    }).catchError((e) => _showError(e));
  }
`

Thnx !!

**Comment by itsmejohndoe** [comment]
Hey @Nemasio! I'm having this issue too, but only within the release version :( Which version are you using? I'm on 1.1.14.

**Comment by iamsandeepsk** [comment]
I'm having this issue too

**Comment by Akorius** [comment]
A year later, I keep getting the same problem on 2.0.0

**Comment by staticgsm** [comment]
> Hey, this exception is ocurring to me, anyone has any idea how to solve the issue?
> It happens when checkForUpdate future function returns.
> "No implementation found for method checkForUpdate on channel in_app_update"
> 
> Also when i now do FLUTTER RUN, says this:
> The plugin `in_app_update` requires your app to be migrated to the Android embedding v2. Follow the steps on
> https://flutter.dev/go/android-project-migration and re-run this command.
> 
> Im running Flutter version 1.20.4
> 
> `
> void _actualizarAppAndroid(){
> 
> ```
> print('Verificando si hay nueva version');
> InAppUpdate.checkForUpdate()
> .then((info) {
>   setState(() {
>     _updateInfo = info;
> 
>     if (_updateInfo?.updateAvailable == true) {
>         print('Hay Update');
> 
>         InAppUpdate.startFlexibleUpdate()
>           .then((_) {
>             setState(() {
>               print('Comenzar flex Update');
>               _flexibleUpdateAvailable = true;
>               /*InAppUpdate.completeFlexibleUpdate().then((_) {
>                       _scaffoldKey.currentState.showSnackBar(SnackBar(content: Text('Success!')));
>                     }).catchError((e) => _showError(e));*/
>             });
>         }).catchError((e) => _showError(e));
>     }
>   });
> }).catchError((e) => _showError(e));
> ```
> 
> }
> `
> 
> Thnx !!

instead of 
if (_updateInfo?.updateAvailable == true) 
use
if (_updateInfo?.flexibleUpdateAllowed == true)

check with in_app_update: 2.0.0 & flutter 2.2.1
