### ISSUE TITLE
Build Error on the latest gradle: Gradle-6.5.+ 

### ISSUE THREAD

**Issue by Melak12** [feilfeilundfeil/flutter_in_app_update#55]
When building the app using the latest Gradle version (6.5.+) the following exception is occurred: 

`Note: Recompile with -Xlint: deprecation for details.
e: C:\Users\Melak\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\in_app_update-1.1.14\android\src\main\kotlin\de\ffuf\in_app_update\InAppUpdatePlugin.kt: (30, 1): Class 'InAppUpdatePlugin' is not abstract and does not implement abstract member public abstract fun onActivityCreated(p0: Activity, p1: Bundle?): Unit defined in android.app.Application.ActivityLifecycleCallbacks
e: C:\Users\Melak\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\in_app_update-1.1.14\android\src\main\kotlin\de\ffuf\in_app_update\InAppUpdatePlugin.kt: (114, 5): 'onActivityCreated' overrides nothing
e: C:\Users\Melak\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\in_app_update-1.1.14\android\src\main\kotlin\de\ffuf\in_app_update\InAppUpdatePlugin.kt: (116, 5): 'onActivityPaused' overrides nothing
e: C:\Users\Melak\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\in_app_update-1.1.14\android\src\main\kotlin\de\ffuf\in_app_update\InAppUpdatePlugin.kt: (118, 5): 'onActivityStarted' overrides nothing
e: C:\Users\Melak\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\in_app_update-1.1.14\android\src\main\kotlin\de\ffuf\in_app_update\InAppUpdatePlugin.kt: (120, 5): 'onActivityDestroyed' overrides nothing
e: C:\Users\Melak\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\in_app_update-1.1.14\android\src\main\kotlin\de\ffuf\in_app_update\InAppUpdatePlugin.kt: (122, 5): 'onActivitySaveInstanceState' overrides nothing
e: C:\Users\Melak\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\in_app_update-1.1.14\android\src\main\kotlin\de\ffuf\in_app_update\InAppUpdatePlugin.kt: (124, 5): 'onActivityStopped' overrides nothing
e: C:\Users\Melak\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\in_app_update-1.1.14\android\src\main\kotlin\de\ffuf\in_app_update\InAppUpdatePlugin.kt: (126, 5): 'onActivityResumed' overrides nothing

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':in_app_update:compileDebugKotlin'.`

**Comment by dhrn** [comment]
any update?

**Comment by Melak12** [comment]
Not yet. I just downgrade the grade to resolve my issue

**Comment by dhrn** [comment]
@jonasbark any update?

**Comment by jonasbark** [comment]
Feel free to make a pull request with the fix 👍

**Comment by dhrn** [comment]
@jonasbark I don't any idea about this. throw some light here.

**Comment by mig35** [comment]
fixed in https://github.com/feilfeilundfeil/flutter_in_app_update/pull/56

@Melak12 @dhrn 
feel free to use this code while PR is not merged:

  in_app_update: 
    git:
      url: git@github.com:mig35/flutter_in_app_update.git
      ref: bugfix/55

**Comment by jonasbark** [comment]
1.1.5 was just published - much appreciated @mig35

**Comment by Melak12** [comment]
Thanks and much appreciated!
