### ISSUE TITLE
checkForUpdate getting ERROR_APP_NOT_OWNED error.

### ISSUE THREAD

**Issue by shinewanna** [feilfeilundfeil/flutter_in_app_update#58]
![Screen Shot 2021-02-02 at 1 30 46 PM](https://user-images.githubusercontent.com/39454969/106563935-f3ff7800-655a-11eb-8572-74a0851dfeff.png)

Do i need to configure more?
My app is already in Play Store

**Comment by jonasbark** [comment]
Did you read the link? You can't try this with an app you installed locally, e.g. during debugging
