### ISSUE TITLE
Update this library to Darts null safety

### ISSUE THREAD

**Issue by ueman** [feilfeilundfeil/flutter_in_app_update#60]
The next stable release of Flutter is using most probably Darts new null safety feature.
Thus this library should be migrated.

Please see the following links for further information:
https://dart.dev/null-safety/migration-guide
https://medium.com/flutter/announcing-dart-null-safety-beta-4491da22077a

**Comment by IchordeDionysos** [comment]
@jonasbark Would appreciate if null safety support would be coming :) 

The Dart/Flutter team already encourages publishing the migrated packages: See [this blog post](https://medium.com/dartlang/preparing-the-dart-and-flutter-ecosystem-for-null-safety-e550ce72c010).

**Comment by MooNag** [comment]
I will create a PR that migrates master.

**Comment by MooNag** [comment]
#62 fixes this issue.

**Comment by IchordeDionysos** [comment]
The new Dart version with null-safety was just released 😍 
https://medium.com/dartlang/announcing-dart-2-12-499a6e689c87
