### ISSUE TITLE
Continue ask for update

### ISSUE THREAD

**Issue by webaddicted** [feilfeilundfeil/flutter_in_app_update#63]
Hi,

In app update always open even after update app(PFA video).
It's very bed behavior, Please have a look.

BR,
Deepak

https://user-images.githubusercontent.com/38448422/110283178-a668a600-8005-11eb-8131-9c5bc1bd0226.mp4

**Comment by jonasbark** [comment]
Which version? How did you integrate the plugin?

**Comment by webaddicted** [comment]
Hi,

Here is code :

          ` AppUpdateInfo _updateInfo;
            @override
            void initState() {
              super.initState();
              checkForUpdate();
            }`

        `  Future<void> checkForUpdate() async {
            InAppUpdate.checkForUpdate().then((info) {
              print(info);
              _updateInfo =info;
              if(_updateInfo?.updateAvailable == true)
                InAppUpdate.performImmediateUpdate().catchError((e) => print(e.toString()));
            }).catchError((e) =>  print(e.toString()));
          }
        }
        `
**Pubspec.yaml** file  version

version: 1.5.0+5

**Android gradle version**

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '5'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.5.0'
} 

Thanks

**Comment by jonasbark** [comment]
Maybe the APK you uploaded in the Play Store has a higher version code. Check the official documentation from Google, which is linked in the README.

**Comment by webaddicted** [comment]
Yes, I have updated apk on play store with version 1.9.0 uploaded.
And on my device I downgrade version then I'm checking. But t's not working.

**Comment by webaddicted** [comment]
Hi @jonasbark ,

Yes, I have updated apk on play store with version 1.9.0 uploaded.
And on my device I downgrade version 1.6.0  then I'm checking. But t's not working.
