### ISSUE TITLE
App is downloading the updates but not installing

### ISSUE THREAD

**Issue by bhushanudupa** [feilfeilundfeil/flutter_in_app_update#64]
Hello @jonasbark 
Hope you are doing great!!
I have been using this package from past two days. I might not have understood the functionality of the package.
`  AppUpdateInfo _updateInfo;
`
`  bool _flexibleUpdateAvailable = false;
`
```dart
Future<void> checkForUpdate() async {
    InAppUpdate.checkForUpdate().then((info) {
      setState(() {
        _updateInfo = info;
      });
    }).catchError((e) {
      _showError(e.toString());
    });
  }
  
  ElevatedButton(
                  child: Text('Start flexible update'),
                  onPressed: _updateInfo?.updateAvailability ==
                          UpdateAvailability.updateAvailable
                      ? () {
                          InAppUpdate.startFlexibleUpdate().then((_) {
                            setState(() {
                              _flexibleUpdateAvailable = true;
                            });
                          }).catchError((e) {
                            _showError(e.toString());
                          });
                        }
                      : null,
                ),
                ElevatedButton(
                  child: Text('Complete flexible update'),
                  onPressed: !_flexibleUpdateAvailable
                      ? null
                      : () {
                          InAppUpdate.completeFlexibleUpdate().then((_) {
                            _showError("Success!");
                          }).catchError((e) {
                            _showError(e.toString());
                          });
                        },
                )
```
This is my code.
But when I Click on **`Complete flexible update`** button, it shows it is installing updates but it will display the contents of previous version after installing the updates.

FYI, I'm running it in debug mode.
Please help me.

**Comment by rjohannengabriel** [comment]
> Hello @jonasbark
> Hope you are doing great!!
> I have been using this package from past two days. I might not have understood the functionality of the package.
> ` AppUpdateInfo _updateInfo;`
> ` bool _flexibleUpdateAvailable = false;`
> 
> ```dart
> Future<void> checkForUpdate() async {
>     InAppUpdate.checkForUpdate().then((info) {
>       setState(() {
>         _updateInfo = info;
>       });
>     }).catchError((e) {
>       _showError(e.toString());
>     });
>   }
>   
>   ElevatedButton(
>                   child: Text('Start flexible update'),
>                   onPressed: _updateInfo?.updateAvailability ==
>                           UpdateAvailability.updateAvailable
>                       ? () {
>                           InAppUpdate.startFlexibleUpdate().then((_) {
>                             setState(() {
>                               _flexibleUpdateAvailable = true;
>                             });
>                           }).catchError((e) {
>                             _showError(e.toString());
>                           });
>                         }
>                       : null,
>                 ),
>                 ElevatedButton(
>                   child: Text('Complete flexible update'),
>                   onPressed: !_flexibleUpdateAvailable
>                       ? null
>                       : () {
>                           InAppUpdate.completeFlexibleUpdate().then((_) {
>                             _showError("Success!");
>                           }).catchError((e) {
>                             _showError(e.toString());
>                           });
>                         },
>                 )
> ```
> 
> This is my code.
> But when I Click on **`Complete flexible update`** button, it shows it is installing updates but it will display the contents of previous version after installing the updates.
> 
> FYI, I'm running it in debug mode.
> Please help me.

This was the same case for me when running it on debug mode. It's probably because the signatures are different from Play Store as Play Store signs the releases while local builds aren't (I'm not sure this is just a speculation)

I tried releasing my update on Play Store and it properly installs the new update.

**Comment by jonasbark** [comment]
Yes, as mentioned in https://github.com/feilfeilundfeil/flutter_in_app_update#getting-error_api_not_available-error :)
