### ISSUE TITLE
Provide available version code

### ISSUE THREAD

**Issue by cmkweber** [feilfeilundfeil/flutter_in_app_update#7]
This is exposed by the AppUpdateManager:

[https://developer.android.com/reference/com/google/android/play/core/appupdate/AppUpdateInfo.html#availableVersionCode()](https://developer.android.com/reference/com/google/android/play/core/appupdate/AppUpdateInfo.html#availableVersionCode())

**Comment by jonasbark** [comment]
Can you think of a use case where this would be useful?

**Comment by cmkweber** [comment]
One use case is to only force update if the version number is behind on major, or minor version, but not force if only patch version has changed. With the version number the developer can determine if update is required or not.

**Comment by jonasbark** [comment]
True on that, but there's no way to tell if it's a minor or major release based on the version code alone? That would only work if the developer has a specific way of using the code (instead of just incrementing it).
The version name isn't exposed unfortunately.

**Comment by cmkweber** [comment]
Does it not report the whole version string like: 1.0.0 - as it does on the Play Store page?

**Comment by cmkweber** [comment]
My mistake, I didn't thoroughly review what it was reporting, it looks like they just report an integer, not sure why. I'll close this since unfortunately they aren't providing the whole version string.

**Comment by jonasbark** [comment]
I reopened it again - if there's interest and someone finds a legit use case, then I'll make sure it's implemented 👍

**Comment by creativecreatorormaybenot** [comment]
@jonasbark 

In my current implementation, I check against the backend if the outdated version of the app needs to be updated (a newer version is set as required by the backend). If so, I check if there is an in-app update available.  
With the current implementation, I just assume that the available in-app update meets the version requirement defined by my backend (which is reasonable), but it would of course be epic if I could validate that using the package :)

**Comment by jonasbark** [comment]
1.1.4 has just been uploaded with this feature 👍
