### ISSUE TITLE
Remove the close icon for immediate update

### ISSUE THREAD

**Issue by iesmail-znz** [feilfeilundfeil/flutter_in_app_update#71]
Please see [this ](https://stackoverflow.com/questions/68112024/how-to-remove-close-icon-on-inappupdate-screen)question.

**Comment by binish784** [comment]
any leads on this ? or atleast a way to know when the user presses the close btn ?

**Comment by binish784** [comment]
any leads on this ? or atleast a way to know when the user presses the close btn ?

**Comment by knvpk** [comment]
Hi @iesmail-znz and @binish784 , did you guys managed to handle close scenario?

**Comment by iesmail-znz** [comment]
Not yet.

**Comment by kk2211** [comment]
Stuck with the same issue, please let us know if any updates

**Comment by jonasbark** [comment]
The X button is part of the official libraries and thus cannot be altered or removed
