### ISSUE TITLE
update availability always return 1 and available version code is same 

### ISSUE THREAD

**Issue by josephantonyk94** [feilfeilundfeil/flutter_in_app_update#72]
I/PlayCore(21386): UID: [10353]  PID: [21386] AppUpdateService : requestUpdateInfo(com.josephantonyk94.chithram)
I/PlayCore(21386): UID: [10353]  PID: [21386] AppUpdateService : Initiate binding to the service.
I/PlayCore(21386): UID: [10353]  PID: [21386] AppUpdateService : ServiceConnectionImpl.onServiceConnected(ComponentInfo{com.android.vending/com.google.android.finsky.installservice.DevTriggeredUpdateService})
I/PlayCore(21386): UID: [10353]  PID: [21386] AppUpdateService : linkToDeath
I/PlayCore(21386): UID: [10353]  PID: [21386] OnRequestInstallCallback : onRequestInfo
I/PlayCore(21386): UID: [10353]  PID: [21386] AppUpdateService : Unbind from service.

**Comment by staticgsm** [comment]
I'm also facing the same issue

**Comment by ristosaar** [comment]
I have updateAvailability: 1 and avialableVersionCode: 0 no matter how many times I reinstall the live app, internal test track app or run it in development on real device.

**Comment by Sourabh-221B** [comment]
On play store its showing Update for my app but in my flutter application availableVersionCode and updateAvailability never get changed.

**Comment by knvpk** [comment]
Did anybody solved this prob.

**Comment by EngFoggy** [comment]
I have the same problem.
I have released an update in production channel with in_app_update, then other two releases (again, with in_app_update). On the play store I can see there's an update, but in_app_update returns updateAvailability 1 and the version code is the version code of the running app, not the one on the store...

**Comment by jonasbark** [comment]
It's out of the control of this plugin. All it does is get the information from the original Google libraries. If they return older values then there's nothing the plugin can do. 
The numbers returned by the Google lib depend on different factors, such as cache etc. 
Read more about it here: https://developer.android.com/guide/playcore/in-app-updates

**Comment by Ruslanbek0809** [comment]
> At first I had the same problem as you. But I noticed something, the app must be downloaded from the Play Store, and an update must be available as well. If you do this by launching the app from flutter or vscode, it is normal that it does not work. I don't know if I was very clear.

**Comment by pranjalpc99** [comment]
I am also facing the same issue. My old app's version is 1.0.8+19 and the new app's version is 1.0.9+20. In the old app, I am getting updateAvailablity as 1 and availableVersionCode as 19.  Also UpdateAvailability.updateAvailable is 2 and UpdateAvailability.updateNotAvailable is 1. 

I have used Internal app sharing and downloaded the old app from the internal app sharing the link. Also when I open the link for the new app I get the update button on the Google Play store. But I haven't updated the app from Play Store.

**Comment by Ruslanbek0809** [comment]
> I have the same problem. I have released an update in production channel with in_app_update, then other two releases (again, with in_app_update). On the play store I can see there's an update, but in_app_update returns updateAvailability 1 and the version code is the version code of the running app, not the one on the store...
> 
> EDIT: after more than one day, the update become recognized. Sorry to bother you, the plugin actually works, thanks!!

As this guy said, you should wait about a day to make it work. At least in my case
